# -*- coding: utf-8 -*-
"""Opencv

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gT8vbgUxoXvFFxenqdFmTsLnRMA1RYmH
"""

from keras.models import load_model
import matplotlib.pyplot as plt
import numpy as np
import cv2 as cv

model = load_model('/content/model.h5')

def predict_digit(img):
    img = np.array(img)
    #reshaping to support our model input and normalizing
    img = img.reshape(1,28,28,1)
    img = img/255.0
    #predicting the class
    res = model.predict([img])
    return np.argmax(res), max(res)

img = cv.imread('/content/three.png')
gray_img = cv.cvtColor(img, cv.COLOR_BGR2GRAY) 
plt.xticks([]),plt.yticks([])
plt.show()

digit,accuracy = predict_digit(gray_img)
print('Digit = ',digit)
print('Accuracy = ',accuracy*100,'%')